# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  identitydb:
    image: mcr.microsoft.com/mssql/server
    container_name: identitydb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Trung1232003
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_identitydata:/var/opt/mssql
    networks:
      custom:

  identityservice:
    image: ${DOCKER_REGISTRY-}identityservice
    build:
      context: .
      dockerfile: src/Services/Identity/IdentityService/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=identitydb;Database=IdentityDb;User Id=sa;Password=Trung1232003;Encrypt=False;TrustServerCertificate=True
    depends_on:
      - identitydb
    ports:
      - "18080:8080"
      - "18081:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      custom:

  yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: src/ApiGateways/YarpApiGateway/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    depends_on:
      - identityservice
    ports:
      - "6000:8080"
      - "6060:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      custom:

volumes:
  sqlserver_identitydata:

networks:
  custom:
    ipam:
      config:
        - subnet: 10.5.0.0/16
